// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vultr
{
    public static class GetSshKey
    {
        /// <summary>
        /// Get information about a Vultr SSH key. This data source provides the name, public SSH key, and the creation date for your Vultr SSH key.
        /// 
        /// {{% examples %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetSshKeyResult> InvokeAsync(GetSshKeyArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetSshKeyResult>("vultr:index/getSshKey:getSshKey", args ?? new GetSshKeyArgs(), options.WithVersion());
    }


    public sealed class GetSshKeyArgs : Pulumi.InvokeArgs
    {
        [Input("filters")]
        private List<Inputs.GetSshKeyFilterArgs>? _filters;

        /// <summary>
        /// Query parameters for finding SSH keys.
        /// </summary>
        public List<Inputs.GetSshKeyFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetSshKeyFilterArgs>());
            set => _filters = value;
        }

        public GetSshKeyArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetSshKeyResult
    {
        /// <summary>
        /// The date the SSH key was added to your Vultr account.
        /// </summary>
        public readonly string DateCreated;
        public readonly ImmutableArray<Outputs.GetSshKeyFilterResult> Filters;
        /// <summary>
        /// id is the provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the SSH key.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The public SSH key.
        /// </summary>
        public readonly string SshKey;

        [OutputConstructor]
        private GetSshKeyResult(
            string dateCreated,

            ImmutableArray<Outputs.GetSshKeyFilterResult> filters,

            string id,

            string name,

            string sshKey)
        {
            DateCreated = dateCreated;
            Filters = filters;
            Id = id;
            Name = name;
            SshKey = sshKey;
        }
    }
}
