// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vultr
{
    public static class GetUser
    {
        /// <summary>
        /// Get information about a Vultr user associated with your account. This data source provides the name, email, access control list, and API status for a Vultr user associated with your account.
        /// 
        /// {{% examples %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetUserResult> InvokeAsync(GetUserArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetUserResult>("vultr:index/getUser:getUser", args ?? new GetUserArgs(), options.WithVersion());
    }


    public sealed class GetUserArgs : Pulumi.InvokeArgs
    {
        [Input("filters")]
        private List<Inputs.GetUserFilterArgs>? _filters;

        /// <summary>
        /// Query parameters for finding users.
        /// </summary>
        public List<Inputs.GetUserFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetUserFilterArgs>());
            set => _filters = value;
        }

        public GetUserArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetUserResult
    {
        /// <summary>
        /// The access control list for the user.
        /// </summary>
        public readonly ImmutableArray<string> Acls;
        /// <summary>
        /// Whether API is enabled for the user.
        /// </summary>
        public readonly string ApiEnabled;
        /// <summary>
        /// The email of the user.
        /// </summary>
        public readonly string Email;
        public readonly ImmutableArray<Outputs.GetUserFilterResult> Filters;
        /// <summary>
        /// id is the provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the user.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetUserResult(
            ImmutableArray<string> acls,

            string apiEnabled,

            string email,

            ImmutableArray<Outputs.GetUserFilterResult> filters,

            string id,

            string name)
        {
            Acls = acls;
            ApiEnabled = apiEnabled;
            Email = email;
            Filters = filters;
            Id = id;
            Name = name;
        }
    }
}
