// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;

namespace Pulumi.Vultr
{
    public static class Config
    {
        private static readonly Pulumi.Config __config = new Pulumi.Config("vultr");
        /// <summary>
        /// The API Key that allows interaction with the API
        /// </summary>
        public static string? ApiKey { get; set; } = __config.Get("apiKey");

        /// <summary>
        /// Allows users to set the speed of API calls to work with the Vultr Rate Limit
        /// </summary>
        public static int? RateLimit { get; set; } = __config.GetInt32("rateLimit");

        /// <summary>
        /// Allows users to set the maximum number of retries allowed for a failed API call.
        /// </summary>
        public static int? RetryLimit { get; set; } = __config.GetInt32("retryLimit");

    }
}
