// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

let __config = new pulumi.Config("vultr");

/**
 * The API Key that allows interaction with the API
 */
export let apiKey: string | undefined = __config.get("apiKey");
/**
 * Allows users to set the speed of API calls to work with the Vultr Rate Limit
 */
export let rateLimit: number | undefined = __config.getObject<number>("rateLimit");
/**
 * Allows users to set the maximum number of retries allowed for a failed API call.
 */
export let retryLimit: number | undefined = __config.getObject<number>("retryLimit");
