// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides a Vultr bare metal server resource. This can be used to create, read, modify, and delete bare metal servers on your Vultr account.
 * 
 * ## Example Usage
 * 
 * 
 * 
 * ```typescript
 * ```
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-vultr/blob/master/website/docs/r/bare_metal_server.html.markdown.
 */
export class BareMetalServer extends pulumi.CustomResource {
    /**
     * Get an existing BareMetalServer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BareMetalServerState, opts?: pulumi.CustomResourceOptions): BareMetalServer {
        return new BareMetalServer(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'vultr:index/bareMetalServer:BareMetalServer';

    /**
     * Returns true if the given object is an instance of BareMetalServer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BareMetalServer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BareMetalServer.__pulumiType;
    }

    /**
     * The ID of the Vultr application to be installed on the server.
     */
    public readonly appId!: pulumi.Output<string>;
    /**
     * The number of CPUs available on the server.
     */
    public /*out*/ readonly cpuCount!: pulumi.Output<number>;
    /**
     * The date the server was added to your Vultr account.
     */
    public /*out*/ readonly dateCreated!: pulumi.Output<string>;
    /**
     * The server's default password.
     */
    public /*out*/ readonly defaultPassword!: pulumi.Output<string>;
    /**
     * The description of the disk(s) on the server.
     */
    public /*out*/ readonly disk!: pulumi.Output<string>;
    /**
     * Whether the server has IPv6 networking activated.
     */
    public readonly enableIpv6!: pulumi.Output<boolean | undefined>;
    /**
     * The server's IPv4 gateway.
     */
    public /*out*/ readonly gatewayV4!: pulumi.Output<string>;
    /**
     * The hostname to assign to the server.
     */
    public readonly hostname!: pulumi.Output<string | undefined>;
    /**
     * A label for the server.
     */
    public readonly label!: pulumi.Output<string | undefined>;
    /**
     * The server's main IP address.
     */
    public /*out*/ readonly mainIp!: pulumi.Output<string>;
    /**
     * The server's IPv4 netmask.
     */
    public /*out*/ readonly netmaskV4!: pulumi.Output<string>;
    /**
     * Whether an activation email will be sent when the server is ready.
     */
    public readonly notifyActivate!: pulumi.Output<boolean | undefined>;
    /**
     * The string description of the operating system installed on the server.
     */
    public /*out*/ readonly os!: pulumi.Output<string>;
    /**
     * The ID of the operating system to be installed on the server.
     */
    public readonly osId!: pulumi.Output<string>;
    /**
     * The ID of the plan that you want the server to subscribe to.
     */
    public readonly planId!: pulumi.Output<number>;
    /**
     * The amount of memory available on the server in MB.
     */
    public /*out*/ readonly ram!: pulumi.Output<string>;
    /**
     * The ID of the region that the server is to be created in.
     */
    public readonly regionId!: pulumi.Output<number>;
    /**
     * The ID of the startup script you want added to the server.
     */
    public readonly scriptId!: pulumi.Output<string | undefined>;
    /**
     * The ID of the Vultr snapshot that the server will restore for the initial installation. 
     */
    public readonly snapshotId!: pulumi.Output<string | undefined>;
    /**
     * A list of SSH key IDs to apply to the server on install (only valid for Linux/FreeBSD).
     */
    public readonly sshKeyIds!: pulumi.Output<string[] | undefined>;
    /**
     * The status of the server's subscription.
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    /**
     * The tag to assign to the server.
     */
    public readonly tag!: pulumi.Output<string | undefined>;
    /**
     * Generic data store, which some provisioning tools and cloud operating systems use as a configuration file. It is generally consumed only once after an instance has been launched, but individual needs may vary.
     */
    public readonly userData!: pulumi.Output<string | undefined>;
    /**
     * A list of the server's IPv6 networks.
     */
    public /*out*/ readonly v6Networks!: pulumi.Output<{[key: string]: any}[]>;

    /**
     * Create a BareMetalServer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BareMetalServerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BareMetalServerArgs | BareMetalServerState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as BareMetalServerState | undefined;
            inputs["appId"] = state ? state.appId : undefined;
            inputs["cpuCount"] = state ? state.cpuCount : undefined;
            inputs["dateCreated"] = state ? state.dateCreated : undefined;
            inputs["defaultPassword"] = state ? state.defaultPassword : undefined;
            inputs["disk"] = state ? state.disk : undefined;
            inputs["enableIpv6"] = state ? state.enableIpv6 : undefined;
            inputs["gatewayV4"] = state ? state.gatewayV4 : undefined;
            inputs["hostname"] = state ? state.hostname : undefined;
            inputs["label"] = state ? state.label : undefined;
            inputs["mainIp"] = state ? state.mainIp : undefined;
            inputs["netmaskV4"] = state ? state.netmaskV4 : undefined;
            inputs["notifyActivate"] = state ? state.notifyActivate : undefined;
            inputs["os"] = state ? state.os : undefined;
            inputs["osId"] = state ? state.osId : undefined;
            inputs["planId"] = state ? state.planId : undefined;
            inputs["ram"] = state ? state.ram : undefined;
            inputs["regionId"] = state ? state.regionId : undefined;
            inputs["scriptId"] = state ? state.scriptId : undefined;
            inputs["snapshotId"] = state ? state.snapshotId : undefined;
            inputs["sshKeyIds"] = state ? state.sshKeyIds : undefined;
            inputs["status"] = state ? state.status : undefined;
            inputs["tag"] = state ? state.tag : undefined;
            inputs["userData"] = state ? state.userData : undefined;
            inputs["v6Networks"] = state ? state.v6Networks : undefined;
        } else {
            const args = argsOrState as BareMetalServerArgs | undefined;
            if (!args || args.planId === undefined) {
                throw new Error("Missing required property 'planId'");
            }
            if (!args || args.regionId === undefined) {
                throw new Error("Missing required property 'regionId'");
            }
            inputs["appId"] = args ? args.appId : undefined;
            inputs["enableIpv6"] = args ? args.enableIpv6 : undefined;
            inputs["hostname"] = args ? args.hostname : undefined;
            inputs["label"] = args ? args.label : undefined;
            inputs["notifyActivate"] = args ? args.notifyActivate : undefined;
            inputs["osId"] = args ? args.osId : undefined;
            inputs["planId"] = args ? args.planId : undefined;
            inputs["regionId"] = args ? args.regionId : undefined;
            inputs["scriptId"] = args ? args.scriptId : undefined;
            inputs["snapshotId"] = args ? args.snapshotId : undefined;
            inputs["sshKeyIds"] = args ? args.sshKeyIds : undefined;
            inputs["tag"] = args ? args.tag : undefined;
            inputs["userData"] = args ? args.userData : undefined;
            inputs["cpuCount"] = undefined /*out*/;
            inputs["dateCreated"] = undefined /*out*/;
            inputs["defaultPassword"] = undefined /*out*/;
            inputs["disk"] = undefined /*out*/;
            inputs["gatewayV4"] = undefined /*out*/;
            inputs["mainIp"] = undefined /*out*/;
            inputs["netmaskV4"] = undefined /*out*/;
            inputs["os"] = undefined /*out*/;
            inputs["ram"] = undefined /*out*/;
            inputs["status"] = undefined /*out*/;
            inputs["v6Networks"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(BareMetalServer.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering BareMetalServer resources.
 */
export interface BareMetalServerState {
    /**
     * The ID of the Vultr application to be installed on the server.
     */
    readonly appId?: pulumi.Input<string>;
    /**
     * The number of CPUs available on the server.
     */
    readonly cpuCount?: pulumi.Input<number>;
    /**
     * The date the server was added to your Vultr account.
     */
    readonly dateCreated?: pulumi.Input<string>;
    /**
     * The server's default password.
     */
    readonly defaultPassword?: pulumi.Input<string>;
    /**
     * The description of the disk(s) on the server.
     */
    readonly disk?: pulumi.Input<string>;
    /**
     * Whether the server has IPv6 networking activated.
     */
    readonly enableIpv6?: pulumi.Input<boolean>;
    /**
     * The server's IPv4 gateway.
     */
    readonly gatewayV4?: pulumi.Input<string>;
    /**
     * The hostname to assign to the server.
     */
    readonly hostname?: pulumi.Input<string>;
    /**
     * A label for the server.
     */
    readonly label?: pulumi.Input<string>;
    /**
     * The server's main IP address.
     */
    readonly mainIp?: pulumi.Input<string>;
    /**
     * The server's IPv4 netmask.
     */
    readonly netmaskV4?: pulumi.Input<string>;
    /**
     * Whether an activation email will be sent when the server is ready.
     */
    readonly notifyActivate?: pulumi.Input<boolean>;
    /**
     * The string description of the operating system installed on the server.
     */
    readonly os?: pulumi.Input<string>;
    /**
     * The ID of the operating system to be installed on the server.
     */
    readonly osId?: pulumi.Input<string>;
    /**
     * The ID of the plan that you want the server to subscribe to.
     */
    readonly planId?: pulumi.Input<number>;
    /**
     * The amount of memory available on the server in MB.
     */
    readonly ram?: pulumi.Input<string>;
    /**
     * The ID of the region that the server is to be created in.
     */
    readonly regionId?: pulumi.Input<number>;
    /**
     * The ID of the startup script you want added to the server.
     */
    readonly scriptId?: pulumi.Input<string>;
    /**
     * The ID of the Vultr snapshot that the server will restore for the initial installation. 
     */
    readonly snapshotId?: pulumi.Input<string>;
    /**
     * A list of SSH key IDs to apply to the server on install (only valid for Linux/FreeBSD).
     */
    readonly sshKeyIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The status of the server's subscription.
     */
    readonly status?: pulumi.Input<string>;
    /**
     * The tag to assign to the server.
     */
    readonly tag?: pulumi.Input<string>;
    /**
     * Generic data store, which some provisioning tools and cloud operating systems use as a configuration file. It is generally consumed only once after an instance has been launched, but individual needs may vary.
     */
    readonly userData?: pulumi.Input<string>;
    /**
     * A list of the server's IPv6 networks.
     */
    readonly v6Networks?: pulumi.Input<pulumi.Input<{[key: string]: any}>[]>;
}

/**
 * The set of arguments for constructing a BareMetalServer resource.
 */
export interface BareMetalServerArgs {
    /**
     * The ID of the Vultr application to be installed on the server.
     */
    readonly appId?: pulumi.Input<string>;
    /**
     * Whether the server has IPv6 networking activated.
     */
    readonly enableIpv6?: pulumi.Input<boolean>;
    /**
     * The hostname to assign to the server.
     */
    readonly hostname?: pulumi.Input<string>;
    /**
     * A label for the server.
     */
    readonly label?: pulumi.Input<string>;
    /**
     * Whether an activation email will be sent when the server is ready.
     */
    readonly notifyActivate?: pulumi.Input<boolean>;
    /**
     * The ID of the operating system to be installed on the server.
     */
    readonly osId?: pulumi.Input<string>;
    /**
     * The ID of the plan that you want the server to subscribe to.
     */
    readonly planId: pulumi.Input<number>;
    /**
     * The ID of the region that the server is to be created in.
     */
    readonly regionId: pulumi.Input<number>;
    /**
     * The ID of the startup script you want added to the server.
     */
    readonly scriptId?: pulumi.Input<string>;
    /**
     * The ID of the Vultr snapshot that the server will restore for the initial installation. 
     */
    readonly snapshotId?: pulumi.Input<string>;
    /**
     * A list of SSH key IDs to apply to the server on install (only valid for Linux/FreeBSD).
     */
    readonly sshKeyIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The tag to assign to the server.
     */
    readonly tag?: pulumi.Input<string>;
    /**
     * Generic data store, which some provisioning tools and cloud operating systems use as a configuration file. It is generally consumed only once after an instance has been launched, but individual needs may vary.
     */
    readonly userData?: pulumi.Input<string>;
}
