// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Get information about a Vultr bare metal server.
 * 
 * ## Example Usage
 * 
 * 
 * 
 * ```typescript
 * ```
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-vultr/blob/master/website/docs/d/bare_metal_server.html.markdown.
 */
export function getBareMetalServer(args?: GetBareMetalServerArgs, opts?: pulumi.InvokeOptions): Promise<GetBareMetalServerResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("vultr:index/getBareMetalServer:getBareMetalServer", {
        "filters": args.filters,
    }, opts);
}

/**
 * A collection of arguments for invoking getBareMetalServer.
 */
export interface GetBareMetalServerArgs {
    /**
     * Query parameters for finding servers.
     */
    readonly filters?: inputs.GetBareMetalServerFilter[];
}

/**
 * A collection of values returned by getBareMetalServer.
 */
export interface GetBareMetalServerResult {
    /**
     * The server's application ID.
     */
    readonly appId: string;
    /**
     * The number of CPUs available on the server.
     */
    readonly cpuCount: number;
    /**
     * The date the server was added to your Vultr account.
     */
    readonly dateCreated: string;
    /**
     * The server's default password.
     */
    readonly defaultPassword: string;
    /**
     * The description of the disk(s) on the server.
     */
    readonly disk: string;
    readonly filters?: outputs.GetBareMetalServerFilter[];
    /**
     * The server's IPv4 gateway.
     */
    readonly gatewayV4: string;
    /**
     * The server's label.
     */
    readonly label: string;
    /**
     * The location of the server.
     */
    readonly location: string;
    /**
     * The server's main IP address.
     */
    readonly mainIp: string;
    /**
     * The server's IPv4 netmask.
     */
    readonly netmaskV4: string;
    /**
     * The operating system of the server.
     */
    readonly os: string;
    /**
     * The server's operating system ID.
     */
    readonly osId: string;
    /**
     * The server's plan ID.
     */
    readonly planId: number;
    /**
     * The amount of memory available on the server in MB.
     */
    readonly ram: string;
    /**
     * The region ID (`DCID` in the Vultr API) of the server.
     */
    readonly regionId: number;
    /**
     * The status of the server's subscription.
     */
    readonly status: string;
    /**
     * The server's tag.
     */
    readonly tag: string;
    /**
     * A list of the server's IPv6 networks.
     */
    readonly v6Networks: {[key: string]: any}[];
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
