// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Get information about a Vultr reserved IP address.
 * 
 * ## Example Usage
 * 
 * 
 * 
 * ```typescript
 * ```
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-vultr/blob/master/website/docs/d/reserved_ip.html.markdown.
 */
export function getReservedIP(args?: GetReservedIPArgs, opts?: pulumi.InvokeOptions): Promise<GetReservedIPResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("vultr:index/getReservedIP:getReservedIP", {
        "filters": args.filters,
    }, opts);
}

/**
 * A collection of arguments for invoking getReservedIP.
 */
export interface GetReservedIPArgs {
    /**
     * Query parameters for finding reserved IP addresses.
     */
    readonly filters?: inputs.GetReservedIPFilter[];
}

/**
 * A collection of values returned by getReservedIP.
 */
export interface GetReservedIPResult {
    /**
     * The ID of the VPS the reserved IP is attached to.
     */
    readonly attachedToVps: string;
    readonly filters?: outputs.GetReservedIPFilter[];
    /**
     * The IP type of the reserved IP.
     */
    readonly ipType: string;
    /**
     * The label of the reserved IP.
     */
    readonly label: string;
    /**
     * The ID of the region that the reserved IP is in.
     */
    readonly regionId: number;
    /**
     * The subnet of the reserved IP.
     */
    readonly subnet: string;
    /**
     * The subnet size of the reserved IP.
     */
    readonly subnetSize: number;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
