// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Get information about a Vultr startup script. This data source provides the name, script, type, creation date, and the last modification date for your Vultr startup script.
 * 
 * ## Example Usage
 * 
 * 
 * 
 * ```typescript
 * ```
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-vultr/blob/master/website/docs/d/startup_script.html.markdown.
 */
export function getStartupScript(args?: GetStartupScriptArgs, opts?: pulumi.InvokeOptions): Promise<GetStartupScriptResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("vultr:index/getStartupScript:getStartupScript", {
        "filters": args.filters,
    }, opts);
}

/**
 * A collection of arguments for invoking getStartupScript.
 */
export interface GetStartupScriptArgs {
    /**
     * Query parameters for finding startup scripts.
     */
    readonly filters?: inputs.GetStartupScriptFilter[];
}

/**
 * A collection of values returned by getStartupScript.
 */
export interface GetStartupScriptResult {
    /**
     * The date the startup script was added to your Vultr account.
     */
    readonly dateCreated: string;
    /**
     * The date the startup script was last modified.
     */
    readonly dateModified: string;
    readonly filters?: outputs.GetStartupScriptFilter[];
    /**
     * The name of the startup script.
     */
    readonly name: string;
    /**
     * The contents of the startup script.
     */
    readonly script: string;
    /**
     * The type of the startup script.
     */
    readonly type: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
