// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides a Vultr User resource. This can be used to create, read, modify, and delete Users.
 * 
 * ## Example Usage
 * 
 * 
 * 
 * ```typescript
 * ```
 *
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-vultr/blob/master/website/docs/r/user.html.markdown.
 */
export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserState, opts?: pulumi.CustomResourceOptions): User {
        return new User(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'vultr:index/user:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    /**
     * The access control list for the user. 
     */
    public readonly acls!: pulumi.Output<string[] | undefined>;
    /**
     * Whether API is enabled for the user. Default behavior is set to enabled.
     */
    public readonly apiEnabled!: pulumi.Output<boolean | undefined>;
    /**
     * API Key that is assigned to this user.
     */
    public /*out*/ readonly apiKey!: pulumi.Output<string>;
    /**
     * Email for this user.
     */
    public readonly email!: pulumi.Output<string>;
    /**
     * Name for this user.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Password for this user.
     */
    public readonly password!: pulumi.Output<string>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserArgs | UserState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as UserState | undefined;
            inputs["acls"] = state ? state.acls : undefined;
            inputs["apiEnabled"] = state ? state.apiEnabled : undefined;
            inputs["apiKey"] = state ? state.apiKey : undefined;
            inputs["email"] = state ? state.email : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["password"] = state ? state.password : undefined;
        } else {
            const args = argsOrState as UserArgs | undefined;
            if (!args || args.email === undefined) {
                throw new Error("Missing required property 'email'");
            }
            if (!args || args.password === undefined) {
                throw new Error("Missing required property 'password'");
            }
            inputs["acls"] = args ? args.acls : undefined;
            inputs["apiEnabled"] = args ? args.apiEnabled : undefined;
            inputs["email"] = args ? args.email : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["password"] = args ? args.password : undefined;
            inputs["apiKey"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(User.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering User resources.
 */
export interface UserState {
    /**
     * The access control list for the user. 
     */
    readonly acls?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Whether API is enabled for the user. Default behavior is set to enabled.
     */
    readonly apiEnabled?: pulumi.Input<boolean>;
    /**
     * API Key that is assigned to this user.
     */
    readonly apiKey?: pulumi.Input<string>;
    /**
     * Email for this user.
     */
    readonly email?: pulumi.Input<string>;
    /**
     * Name for this user.
     */
    readonly name?: pulumi.Input<string>;
    /**
     * Password for this user.
     */
    readonly password?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * The access control list for the user. 
     */
    readonly acls?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Whether API is enabled for the user. Default behavior is set to enabled.
     */
    readonly apiEnabled?: pulumi.Input<boolean>;
    /**
     * Email for this user.
     */
    readonly email: pulumi.Input<string>;
    /**
     * Name for this user.
     */
    readonly name?: pulumi.Input<string>;
    /**
     * Password for this user.
     */
    readonly password: pulumi.Input<string>;
}
